---
- name: UFW | Apply firewall rules
  hosts: all
  become: true
  tasks:
    - name: Debian family
      block:
        - name: Ensure UFW is installed
          apt:
            name: ufw
            state: present

        - name: Enable UFW
          community.general.ufw:
            state: enabled

        - name: Allow incoming to 443
          community.general.ufw:
            rule: allow
            proto: tcp
            src: "0.0.0.0/0"
            to_port: "443"

        - name: Allow incoming to 80
          community.general.ufw:
            rule: allow
            proto: tcp
            src: "0.0.0.0/0"
            to_port: "80"

        - name: Allow incoming to 8080
          community.general.ufw:
            rule: allow
            proto: tcp
            src: "0.0.0.0/0"
            to_port: "8080"
          when: inventory_hostname == "web02"

      when: ansible_os_family == "Debian"
